#!/usr/bin/env python3
"""Write redirect stubs for the old mdBook URLs of every docs page.

The mdBook book served each page at /docs/<path>.html (README.md as
README.html, the introduction as introduction.html). This site serves them
at /docs/<path>/. Zensical's redirects plugin cannot create a .html source
(it maps it to <path>/index.html, which collides with the page), so this
writes a small static HTML file at each old path instead. Zensical copies
non-Markdown files from docs/ verbatim, so each lands at its old URL.

Each stub redirects with JavaScript (keeping the #fragment, which a meta
refresh drops in some browsers), falls back to a meta refresh and a link,
points search engines at the new URL with rel=canonical, and is noindex.
Re-run after adding, moving or removing pages; stale stubs are removed.

Usage: gen_redirects.py [--write]   (without --write: print a summary)
"""

import html
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs" / "docs"
SITE_URL = "https://captf.io/docs/"
MARKER = "<!-- generated by tools/gen_redirects.py -->"
# Pages new in this site, with no URL in the first (mdBook) edition.
SKIP = {
    "tags.md",
    "developer-guide/docs-workflow.md",
    "developer-guide/website.md",
    "cloud-modules/noop/README.md",
    "cloud-modules/noop/cluster.md",
    "cloud-modules/noop/machine.md",
    "cloud-modules/noop/machinepool.md",
    "reference/resources/README.md",
    "reference/resources/common-fields.md",
    "reference/resources/terraformcluster.md",
    "reference/resources/terraformclustertemplate.md",
    "reference/resources/terraformmachine.md",
    "reference/resources/terraformmachinetemplate.md",
    "reference/resources/terraformmachinepool.md",
    "reference/resources/terraformmachinepooltemplate.md",
    "reference/resources/terraformclusteridentity.md",
}

# Pages of the first edition that this site no longer has, by their old
# URL (relative to the docs root): the title and the page that replaced
# them, relative to the docs root.
MOVED = {
    "reference/api.html": ("API Reference", "reference/resources/"),
}

STUB = """<!doctype html>
{marker}
<html lang="en">
<head>
<meta charset="utf-8">
<title>Moved: {title}</title>
<meta name="robots" content="noindex">
<link rel="canonical" href="{canonical}">
<meta http-equiv="refresh" content="0; url={target}">
<script>location.replace(new URL({target_js}, location.href).href + location.hash)</script>
</head>
<body>
<p>This page has moved to <a href="{target}">{canonical}</a>.</p>
</body>
</html>
"""


def title_of(page: Path) -> str:
    text = page.read_text()
    m = re.search(r"^title:\s*\"?(.+?)\"?\s*$", text, re.M) or re.search(r"^# (.+)$", text, re.M)
    return m.group(1).strip() if m else page.stem


def stubs() -> dict[Path, str]:
    out = {}
    for page in sorted(DOCS.rglob("*.md")):
        rel = page.relative_to(DOCS)
        if rel.as_posix() in SKIP:
            continue
        if rel.name in ("index.md", "README.md"):
            # The docs root came from introduction.md; sections from README.md.
            old = rel.parent / ("introduction.html" if rel.as_posix() == "index.md" else "README.html")
            target = "./"
            new = rel.parent.as_posix() + "/" if rel.parent != Path(".") else ""
        else:
            old = rel.with_suffix(".html")
            target = rel.stem + "/"
            new = rel.with_suffix("").as_posix() + "/"
        out[DOCS / old] = STUB.format(
            marker=MARKER,
            title=html.escape(title_of(page)),
            canonical=SITE_URL + new,
            target=target,
            target_js='"' + target + '"',
        )
    for old, (title, new) in MOVED.items():
        depth = old.count("/")
        target = "../" * depth + new
        out[DOCS / old] = STUB.format(
            marker=MARKER,
            title=html.escape(title),
            canonical=SITE_URL + new,
            target=target,
            target_js='"' + target + '"',
        )
    return out


def main(argv: list[str]) -> int:
    write = "--write" in argv
    wanted = stubs()
    stale = [p for p in DOCS.rglob("*.html") if MARKER in p.read_text() and p not in wanted]
    if write:
        for path, body in wanted.items():
            path.write_text(body)
        for path in stale:
            path.unlink()
    print(f"{'wrote' if write else 'would write'} {len(wanted)} redirect stubs; {'removed' if write else 'would remove'} {len(stale)} stale")
    if not write:
        for path in list(wanted)[:4]:
            print("  ", path.relative_to(ROOT / "docs"))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
