#!/usr/bin/env python3
"""Regenerate the drawer's "Recent posts" list in zensical.toml.

On blog pages the navigation drawer shows the blog, not the docs
(overrides/partials/nav.html), and under it the newest posts. The blog
plugin keeps posts out of the nav, so the list is data: one
[[project.extra.recent_posts]] table per post, with its title, its date
(ISO, and as shown) and its URL. This writes them from
docs/blog/posts/*.md, newest first (at most MAX), between the BEGIN/END
markers in zensical.toml, and leaves the rest alone.

A post's URL follows the blog plugin's post_url_format, "{date}/{slug}":
blog/YYYY/MM/DD/<slug>/, so every post needs a `slug:` in its front
matter. Re-run after adding or retitling a post.

Usage: gen_blog_nav.py [--write]   (without --write: print the tables)
"""

import json
import sys
from datetime import date
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
CONFIG = ROOT / "zensical.toml"
POSTS = ROOT / "docs" / "blog" / "posts"
BEGIN = "# BEGIN recent posts (generated by tools/gen_blog_nav.py; do not edit)"
END = "# END recent posts"
MAX = 5


def front_matter(path: Path) -> dict:
    text = path.read_text()
    return yaml.safe_load(text[4:text.index("\n---", 4)]) or {}


def posts() -> list[dict]:
    out = []
    for path in POSTS.glob("*.md"):
        meta = front_matter(path)
        if meta.get("draft"):
            continue
        day = meta["date"]
        day = day.get("created") if isinstance(day, dict) else day
        if not isinstance(day, date):
            day = date.fromisoformat(str(day))
        if not meta.get("slug"):
            sys.exit(f"{path.relative_to(ROOT)}: no slug: in front matter")
        out.append({"title": meta["title"], "date": day.isoformat(),
                    "when": f"{day:%B} {day.day}, {day.year}",
                    "href": f"blog/{day:%Y/%m/%d}/{meta['slug']}/"})
    return sorted(out, key=lambda p: p["date"], reverse=True)[:MAX]


def block(entries: list[dict]) -> str:
    lines = [BEGIN]
    for e in entries:
        lines += ["[[project.extra.recent_posts]]",
                  f"title = {json.dumps(e['title'], ensure_ascii=False)}",
                  f"date = {json.dumps(e['date'])}",
                  f"when = {json.dumps(e['when'])}",
                  f"href = {json.dumps(e['href'])}"]
    return "\n".join(lines + [END])


def main(argv: list[str]) -> int:
    new = block(posts())
    if "--write" not in argv:
        print(new)
        return 0
    text = CONFIG.read_text()
    start, end = text.index(BEGIN), text.index(END) + len(END)
    if text[start:end] != new:
        CONFIG.write_text(text[:start] + new + text[end:])
        print(f"wrote {new.count('[[')} recent posts")
    else:
        print("recent posts unchanged")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
