#!/usr/bin/env python3
# Copyright 2026 The CAPTF Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Regenerate the llms.txt sections in zensical.toml from the nav.

llms.txt (https://llmstxt.org) is a Markdown index of the site for LLM
tools: a title, a summary, then sections of links, each with a one-line
description. Zensical's llmstxt plugin writes it from
[project.plugins.llmstxt], whose `sections` map a heading to entries of
{path: description}. Globs work but carry no descriptions, so this lists
every page explicitly:

  - "Start here": the landing page, the docs introduction, Quick Start;
  - one section per nav tab, in nav order, each page with the
    `description:` from its front matter;
  - "Blog": every post, newest first.

It rewrites everything between the BEGIN/END markers in zensical.toml and
leaves the rest alone. Re-run after adding, moving or describing pages.

Usage: gen_llms.py [--write]   (without --write: print the sections)
"""

import json
import re
import sys
import tomllib
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
CONFIG = ROOT / "zensical.toml"
DOCS = ROOT / "docs"
BEGIN = "# BEGIN llmstxt sections (generated by tools/gen_llms.py; do not edit)"
END = "# END llmstxt sections"
START_HERE = ["index.md", "docs/index.md", "docs/getting-started/quick-start.md"]


def front_matter(path: Path) -> dict:
    text = path.read_text()
    if not text.startswith("---\n"):
        return {}
    return yaml.safe_load(text[4:text.index("\n---", 4)]) or {}


def describe(rel: str) -> str:
    meta = front_matter(DOCS / rel)
    return " ".join(str(meta.get("description", "")).split())


def pages(item) -> list[str]:
    if isinstance(item, str):
        return [item]
    if isinstance(item, dict):
        return [p for v in item.values() for p in pages(v)]
    return [p for v in item for p in pages(v)]


def sections() -> list[tuple[str, list[str]]]:
    nav = tomllib.loads(CONFIG.read_text())["project"]["nav"]
    out = [("Start here", START_HERE)]
    for tab in nav:
        (title, value), = tab.items()
        if title == "Blog":
            posts = sorted((DOCS / "blog" / "posts").glob("*.md"), reverse=True)
            out.append(("Blog", [p.relative_to(DOCS).as_posix() for p in posts]))
            continue
        out.append((title, [p for p in pages(value) if p not in START_HERE]))
    return out


def render() -> str:
    lines = [BEGIN, "[project.plugins.llmstxt.sections]"]
    for title, paths in sections():
        lines.append(f"{json.dumps(title)} = [")
        for rel in paths:
            lines.append(f"  {{ {json.dumps(rel)} = {json.dumps(describe(rel))} }},")
        lines.append("]")
    lines.append(END)
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    text = CONFIG.read_text()
    block = render()
    missing = [rel for _, paths in sections() for rel in paths if not describe(rel)]
    if "--write" not in argv:
        print(block)
    else:
        pattern = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
        if not pattern.search(text):
            sys.exit(f"markers not found in {CONFIG.name}; add the BEGIN/END lines once")
        CONFIG.write_text(pattern.sub(lambda _: block, text))
        tomllib.loads(CONFIG.read_text())  # still valid TOML
    total = sum(len(p) for _, p in sections())
    print(f"{total} entries in {len(sections())} sections; {len(missing)} without a description {missing[:5]}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
